# app/modules/citas.py
"""
This module handles appointment scheduling for clients.

It provides a simple way for users to get a link to an external scheduling
service, such as Calendly or an n8n workflow.
"""

def request_appointment():
    """
    Provides the user with a link to schedule an appointment.

    Currently, this function returns a hardcoded placeholder link to Calendly.
    The intention is to replace this with a dynamic link generated by an n8n
    workflow or another scheduling service.
    """
    # TODO: Integrate with a real scheduling service or an n8n workflow to
    # provide a dynamic and personalized scheduling link.
    response_text = (
        "Para agendar una cita, por favor utiliza el siguiente enlace: \n\n"
        "[Enlace de Calendly](https://calendly.com/user/appointment-link)"
    )
    return response_text
